// src/pages/index/index.tsx
import React, { useState, useEffect } from 'react'
import { View, Text, Button } from '@tarojs/components'
import F2 from '@antv/f2'
import goldPriceService from '../../utils/gold-price-service'
import './index.css'

// Define TypeScript interfaces
interface GoldPrice {
  name: string;
  price: string;
  unit: string;
}

interface CurrentPrices {
  au9999: GoldPrice;
  au999: GoldPrice;
  au100: GoldPrice;
  international: GoldPrice;
}

interface PriceTrend {
  trend: 'up' | 'down';
  change: string;
  direction: string;
}

interface PricePoint {
  time: string;
  price: number;
}

const Index: React.FC = () => {
  const [goldPrices, setGoldPrices] = useState<CurrentPrices | null>(null)
  const [loading, setLoading] = useState<boolean>(true)
  const [lastUpdated, setLastUpdated] = useState<string | null>(null)
  const [priceTrend, setPriceTrend] = useState<PriceTrend | null>(null)
  const [priceHistory, setPriceHistory] = useState<PricePoint[]>([])

  // Function to fetch gold prices
  const fetchGoldPrices = async () => {
    setLoading(true)
    try {
      // Simulate API call with mock data
      setTimeout(() => {
        const prices = goldPriceService.getCurrentPrices()
        const trend = goldPriceService.getPriceTrend()
        
        setGoldPrices(prices)
        setPriceTrend(trend)
        setLastUpdated(new Date().toLocaleString())
        setLoading(false)
        
        // Add to price history
        const currentTime = new Date().toLocaleTimeString()
        const currentPrice = parseFloat(prices.au9999.price)
        setPriceHistory(prev => {
          const newHistory = [...prev, { time: currentTime, price: currentPrice }]
          // Keep only last 10 data points
          return newHistory.slice(-10)
        })
      }, 500)
    } catch (error) {
      console.error('Error fetching gold prices:', error)
      setLoading(false)
    }
  }

  useEffect(() => {
    // Initial load
    fetchGoldPrices()
    
    // Set up interval to simulate real-time updates
    const interval = setInterval(fetchGoldPrices, 5000)
    
    return () => clearInterval(interval)
  }, [])

  const handleRefresh = () => {
    fetchGoldPrices()
  }

  return (
    <View className='p-5 flex flex-col items-center min-h-screen bg-white'>
      <Text className='text-2xl font-bold mb-8 text-gray-800'>实时金价查询</Text>
      
      <View className='w-full max-w-xs p-5 border border-gray-300 rounded-lg bg-gray-50 text-center mb-5'>
        {loading ? (
          <Text className='text-lg text-gray-500'>正在获取金价...</Text>
        ) : (
          <>
            <Text className='text-base text-gray-600 block mb-3'>当前金价:</Text>
            
            {/* Display different gold types */}
            {goldPrices && (
              <View className='mb-3'>
                <View className='flex justify-between py-2 border-b border-dashed border-gray-300'>
                  <Text className='text-sm text-gray-700'>{goldPrices.au9999.name}</Text>
                  <Text className='text-base font-bold text-yellow-600'>¥{goldPrices.au9999.price}/克</Text>
                </View>
                
                <View className='flex justify-between py-2 border-b border-dashed border-gray-300'>
                  <Text className='text-sm text-gray-700'>{goldPrices.au999.name}</Text>
                  <Text className='text-base font-bold text-yellow-600'>¥{goldPrices.au999.price}/克</Text>
                </View>
                
                <View className='flex justify-between py-2 border-b border-dashed border-gray-300'>
                  <Text className='text-sm text-gray-700'>{goldPrices.au100.name}</Text>
                  <Text className='text-base font-bold text-yellow-600'>¥{goldPrices.au100.price}/克</Text>
                </View>
                
                <View className='flex justify-between py-2'>
                  <Text className='text-sm text-gray-700'>{goldPrices.international.name}</Text>
                  <Text className='text-base font-bold text-yellow-600'>{goldPrices.international.price}{goldPrices.international.unit}</Text>
                </View>
              </View>
            )}
            
            {/* Display trend */}
            {priceTrend && (
              <View className={`flex justify-center items-center my-4 p-3 rounded ${priceTrend.trend === 'up' ? 'bg-green-50 border border-green-200' : 'bg-red-50 border border-red-200'}`}>
                <Text className={`font-bold mr-2 ${priceTrend.trend === 'up' ? 'text-green-600' : 'text-red-600'}`}>
                  {priceTrend.direction}{priceTrend.change}%
                </Text>
                <Text className='text-sm text-gray-600'>
                  {priceTrend.trend === 'up' ? '价格上涨' : '价格下跌'}
                </Text>
              </View>
            )}
            
            <Text className='text-xs text-gray-500 block mt-3'>最后更新: {lastUpdated}</Text>
          </>
        )}
      </View>
      
      {/* Chart Section */}
      <View className='w-full max-w-xs mb-5'>
        <Text className='block text-center text-sm font-medium text-gray-700 mb-2'>金价趋势图</Text>
        {priceHistory.length > 1 ? (
          <View 
            className='h-48 border border-gray-200 rounded bg-white p-2'
            id="gold-price-chart"
          >
            <Text className='text-gray-500 text-center block'>图表将在小程序中渲染</Text>
          </View>
        ) : (
          <View className='h-48 flex items-center justify-center border border-gray-200 rounded bg-gray-50'>
            <Text className='text-gray-500'>数据收集中的图表</Text>
          </View>
        )}
      </View>
      
      <Button className='bg-blue-500 text-white rounded p-3 mb-5 text-base' onClick={handleRefresh}>
        刷新价格
      </Button>
      
      <View className='p-4 bg-gray-100 rounded w-full max-w-xs text-center'>
        <Text className='text-sm text-gray-600'>注意：此为实时金价参考，实际购买价格请以银行柜台为准</Text>
      </View>
    </View>
  )
}

export default Index

// src/pages/index/index.vue
<template>
  <view class="container">
    <view class="title">实时金价查询</view>
    
    <view class="price-card">
      <view v-if="loading" class="loading">正在获取金价...</view>
      
      <view v-else class="price-content">
        <view class="price-list">
          <view class="price-row">
            <text class="price-name">{{ goldPrices?.au9999?.name }}</text>
            <text class="price-value">¥{{ goldPrices?.au9999?.price }}/克</text>
          </view>
          
          <view class="price-row">
            <text class="price-name">{{ goldPrices?.au999?.name }}</text>
            <text class="price-value">¥{{ goldPrices?.au999?.price }}/克</text>
          </view>
          
          <view class="price-row">
            <text class="price-name">{{ goldPrices?.au100?.name }}</text>
            <text class="price-value">¥{{ goldPrices?.au100?.price }}/克</text>
          </view>
          
          <view class="price-row">
            <text class="price-name">{{ goldPrices?.international?.name }}</text>
            <text class="price-value">{{ goldPrices?.international?.price }}{{ goldPrices?.international?.unit }}</text>
          </view>
        </view>
        
        <view v-if="priceTrend" :class="['trend', priceTrend.trend === 'up' ? 'trend-up' : 'trend-down']">
          <text :class="['trend-value', priceTrend.trend === 'up' ? 'trend-value-up' : 'trend-value-down']">
            {{ priceTrend.direction }}{{ priceTrend.change }}%
          </text>
          <text class="trend-text">
            {{ priceTrend.trend === 'up' ? '价格上涨' : '价格下跌' }}
          </text>
        </view>
        
        <text class="last-updated">最后更新: {{ lastUpdated }}</text>
      </view>
    </view>
    
    <view class="chart-section">
      <text class="chart-title">金价趋势图</text>
      <view v-if="priceHistory.length > 1" class="chart-container">
        <canvas 
          canvas-id="goldPriceChart" 
          id="goldPriceChart" 
          class="chart-canvas"
          @touchstart="touchHandler"
        />
      </view>
      <view v-else class="chart-placeholder">
        <text>数据收集中...</text>
      </view>
    </view>
    
    <button class="refresh-button" @click="handleRefresh">刷新价格</button>
    
    <view class="notice">
      <text class="notice-text">注意：此为实时金价参考，实际购买价格请以银行柜台为准</text>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from 'vue'
import * as echarts from 'echarts'

interface PricePoint {
  time: string
  price: number
}

interface CurrentPrices {
  au9999: { name: string; price: string }
  au999: { name: string; price: string }
  au100: { name: string; price: string }
  international: { name: string; price: string; unit: string }
}

interface PriceTrend {
  trend: 'up' | 'down'
  direction: string
  change: string
}

const goldPriceService = {
  getCurrentPrices: (): CurrentPrices => {
    const basePrice = 785 + Math.random() * 10
    return {
      au9999: { name: '足金999', price: basePrice.toFixed(2) },
      au999: { name: '足金990', price: (basePrice - 5).toFixed(2) },
      au100: { name: '足金999.9', price: (basePrice + 3).toFixed(2) },
      international: { name: '国际金价', price: (basePrice * 7.2 + 50).toFixed(0), unit: ' 美元/盎司' }
    }
  },
  getPriceTrend: (): PriceTrend => {
    const isUp = Math.random() > 0.5
    const change = (Math.random() * 2).toFixed(2)
    return {
      trend: isUp ? 'up' : 'down',
      direction: isUp ? '↑' : '↓',
      change
    }
  }
}

const goldPrices = ref<CurrentPrices | null>(null)
const loading = ref(true)
const lastUpdated = ref('')
const priceTrend = ref<PriceTrend | null>(null)
const priceHistory = ref<PricePoint[]>([])
let chartInstance: any = null
let timer: ReturnType<typeof setInterval> | null = null

const initChart = () => {
  const query = uni.createSelectorQuery()
  query.select('#goldPriceChart')
    .fields({ node: true, size: true })
    .exec((res: any) => {
      if (res[0]) {
        const canvas = res[0]
        const ctx = canvas.getContext('2d')
        const dpr = uni.getSystemInfoSync().pixelRatio
        
        const width = res[0].width
        const height = res[0].height
        
        canvas.width = width * dpr
        canvas.height = height * dpr
        ctx.scale(dpr, dpr)
        
        chartInstance = echarts.init(canvas as any, null, {
          width,
          height,
          devicePixelRatio: dpr
        })
        
        updateChart()
      }
    })
}

const updateChart = () => {
  if (!chartInstance || priceHistory.value.length <= 1) return

  const prices = priceHistory.value.map(d => d.price)
  const minPrice = Math.min(...prices) * 0.995
  const maxPrice = Math.max(...prices) * 1.005

  const option = {
    tooltip: {
      trigger: 'axis',
      confine: true,
      formatter: (params: any) => {
        if (params && params[0]) {
          return `${params[0].name}<br/>¥${params[0].value}`
        }
        return ''
      }
    },
    grid: {
      left: 50,
      right: 20,
      top: 20,
      bottom: 40
    },
    xAxis: {
      type: 'category',
      data: priceHistory.value.map(d => {
        const parts = d.time.split(':')
        return parts.length >= 2 ? `${parts[0]}:${parts[1]}` : d.time
      }),
      axisLine: { lineStyle: { color: '#e8e8e8' } },
      axisLabel: { color: '#888888', fontSize: 10 }
    },
    yAxis: {
      type: 'value',
      min: minPrice,
      max: maxPrice,
      axisLine: { show: false },
      axisLabel: {
        color: '#888888',
        fontSize: 10,
        formatter: (val: number) => `¥${val.toFixed(0)}`
      },
      splitLine: { lineStyle: { color: '#e8e8e8' } }
    },
    series: [{
      data: priceHistory.value.map(d => d.price),
      type: 'line',
      smooth: true,
      symbol: 'circle',
      symbolSize: 6,
      lineStyle: { color: '#5AD8A6', width: 2 },
      itemStyle: { color: '#5AD8A6', borderColor: '#ffffff', borderWidth: 2 },
      areaStyle: {
        color: {
          type: 'linear',
          x: 0, y: 0, x2: 0, y2: 1,
          colorStops: [
            { offset: 0, color: 'rgba(90, 216, 166, 0.3)' },
            { offset: 1, color: 'rgba(90, 216, 166, 0.02)' }
          ]
        }
      }
    }]
  }

  chartInstance.setOption(option)
}

const fetchGoldPrices = () => {
  loading.value = true
  
  setTimeout(() => {
    const prices = goldPriceService.getCurrentPrices()
    const trend = goldPriceService.getPriceTrend()
    
    goldPrices.value = prices
    priceTrend.value = trend
    lastUpdated.value = new Date().toLocaleString()
    loading.value = false
    
    const currentTime = new Date().toLocaleTimeString()
    const currentPrice = parseFloat(prices.au9999.price)
    
    priceHistory.value = [...priceHistory.value, { time: currentTime, price: currentPrice }].slice(-10)
    
    if (priceHistory.value.length > 1) {
      updateChart()
    }
  }, 500)
}

const handleRefresh = () => {
  fetchGoldPrices()
}

const touchHandler = (e: any) => {
  if (chartInstance) {
    chartInstance.dispatchAction({ type: 'showTip', seriesIndex: 0 })
  }
}

onMounted(() => {
  fetchGoldPrices()
  
  setTimeout(() => {
    if (priceHistory.value.length > 1) {
      initChart()
    }
  }, 1000)
  
  timer = setInterval(() => {
    fetchGoldPrices()
  }, 5000)
})

onUnmounted(() => {
  if (timer) {
    clearInterval(timer)
  }
  if (chartInstance) {
    chartInstance.dispose()
  }
})
</script>

<style lang="scss">
page {
  background-color: #ffffff;
}

.container {
  padding: 40rpx;
  display: flex;
  flex-direction: column;
  align-items: center;
  min-height: 100vh;
  background-color: #ffffff;
}

.title {
  font-size: 48rpx;
  font-weight: bold;
  margin-bottom: 64rpx;
  color: #333333;
}

.price-card {
  width: 600rpx;
  padding: 40rpx;
  border: 1px solid #e0e0e0;
  border-radius: 16rpx;
  background-color: #f9f9f9;
  text-align: center;
  margin-bottom: 40rpx;
}

.loading {
  font-size: 28rpx;
  color: #666666;
}

.price-content {
  width: 100%;
}

.price-list {
  width: 100%;
}

.price-row {
  display: flex;
  justify-content: space-between;
  padding: 16rpx 0;
  border-bottom: 1px dashed #cccccc;
}

.price-name {
  font-size: 26rpx;
  color: #333333;
}

.price-value {
  font-size: 30rpx;
  font-weight: bold;
  color: #d4a017;
}

.trend {
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 32rpx 0;
  padding: 24rpx;
  border-radius: 8rpx;
}

.trend-up {
  background-color: #e8f5e9;
  border: 1px solid #c8e6c9;
}

.trend-down {
  background-color: #ffebee;
  border: 1px solid #ffcdd2;
}

.trend-value {
  font-size: 32rpx;
  font-weight: bold;
  margin-right: 16rpx;
}

.trend-value-up {
  color: #4caf50;
}

.trend-value-down {
  color: #f44336;
}

.trend-text {
  font-size: 26rpx;
  color: #666666;
}

.last-updated {
  display: block;
  margin-top: 24rpx;
  font-size: 22rpx;
  color: #999999;
}

.chart-section {
  width: 600rpx;
  margin-bottom: 40rpx;
}

.chart-title {
  display: block;
  font-size: 32rpx;
  font-weight: bold;
  color: #333333;
  margin-bottom: 20rpx;
  text-align: center;
}

.chart-container {
  height: 400rpx;
  border: 1px solid #e0e0e0;
  border-radius: 8rpx;
  background-color: #ffffff;
  overflow: hidden;
}

.chart-canvas {
  width: 100%;
  height: 100%;
}

.chart-placeholder {
  height: 400rpx;
  display: flex;
  justify-content: center;
  align-items: center;
  border: 1px solid #e0e0e0;
  border-radius: 8rpx;
  background-color: #f9f9f9;
  color: #999999;
}

.refresh-button {
  width: 600rpx;
  height: 88rpx;
  line-height: 88rpx;
  background-color: #1890ff;
  color: #ffffff;
  border-radius: 8rpx;
  font-size: 28rpx;
  margin-bottom: 40rpx;
}

.notice {
  width: 600rpx;
  padding: 20rpx;
  background-color: #fffbe6;
  border: 1px solid #ffe58f;
  border-radius: 8rpx;
}

.notice-text {
  font-size: 22rpx;
  color: #666666;
  line-height: 1.6;
}
</style>
